const express = require('express');
const router  = express.Router();
const c       = require('../controllers/authController');
const { protect } = require('../middleware/auth');
router.post('/register',        c.register);
router.post('/login',           c.login);
router.get('/me',               protect, c.getMe);
router.put('/updatepassword',   protect, c.updatePassword);
router.post('/forgot-password', c.forgotPassword);
router.post('/reset-password',  c.resetPassword);
module.exports = router;
